import { CustomerEmail } from "./types";

type EmailSeed = Omit<CustomerEmail, "history" | "nextActions"> &
  Partial<Pick<CustomerEmail, "history" | "nextActions">>;

const emailSeeds: EmailSeed[] = [
  {
    id: "e1",
    subject: "Ambient mode options on TV-Model 1",
    body: "Hi team, I love the panel but can't find how to enable the ambient gallery mode that was shown in the demo. Can you point me to the right menu on TV-Model 1?",
    sentiment: "positive",
    customerName: "Freja Jensen",
    productModel: "TV-Model 1",
    priority: "medium",
    answered: true,
    history: ["Email received about ambient gallery mode", "Answered with menu steps"],
    nextActions: [],
  },
  {
    id: "e2",
    subject: "Dead pixels out of the box",
    body: "My brand new TV-Model 2 has two dead pixels in the upper right corner. I unboxed it yesterday and would like to know if this is covered under warranty or if I should return it.",
    sentiment: "negative",
    customerName: "Mikkel Andersen",
    productModel: "TV-Model 2",
    priority: "high",
    history: ["Dead pixels reported on new unit", "Asked about warranty coverage options"],
    nextActions: ["Verify purchase details", "Confirm warranty replacement path"],
  },
  {
    id: "e3",
    subject: "Subtitles keep disappearing",
    body: "While streaming, the subtitles on TV-Model 3 randomly disappear every few minutes. Is there a firmware update that fixes this?",
    sentiment: "neutral",
    customerName: "Signe Larsen",
    productModel: "TV-Model 3",
    priority: "medium",
    history: ["Subtitles disappear intermittently", "Requested firmware guidance"],
    nextActions: ["Check firmware version", "Send subtitle stability steps"],
  },
  {
    id: "e4",
    subject: "Wall mount screws missing",
    body: "The wall mount kit for my TV-Model 4 didn't include the shorter screws mentioned in the manual. Can you send replacements or tell me which size to buy?",
    sentiment: "negative",
    customerName: "Anders Madsen",
    productModel: "TV-Model 4",
    priority: "medium",
    history: ["Missing shorter screws in mount kit", "Asked for replacements/size info"],
    nextActions: ["Confirm screw specs", "Ship replacement screws"],
  },
  {
    id: "e5",
    subject: "Impressed with gaming mode",
    body: "Just wanted to say the low latency gaming mode on TV-Model 1 is fantastic. Do you recommend any other settings for PS5 gameplay?",
    sentiment: "positive",
    customerName: "Sofie Kristensen",
    productModel: "TV-Model 1",
    priority: "low",
    history: ["Positive feedback on gaming mode", "Asked for PS5 settings tips"],
    nextActions: ["Share optimized PS5 settings"],
  },
  {
    id: "e6",
    subject: "Audio delay with soundbar",
    body: "I'm getting a noticeable audio delay when using my soundbar over HDMI ARC with TV-Model 2. Is there a lip sync adjustment I should try?",
    sentiment: "neutral",
    customerName: "Kasper Nielsen",
    productModel: "TV-Model 2",
    priority: "high",
    history: ["Audio delay over HDMI ARC", "Asked for lip sync adjustment"],
    nextActions: ["Send lip sync steps", "Offer follow-up if unresolved"],
  },
  {
    id: "e7",
    subject: "Picture too dim in daylight",
    body: "TV-Model 3 looks great at night but is very dim in our bright living room. Are there brightness presets for daytime use?",
    sentiment: "negative",
    customerName: "Camilla Rasmussen",
    productModel: "TV-Model 3",
    priority: "medium",
    answered: true,
    history: ["Picture dim in bright room", "Provided daytime brightness preset"],
    nextActions: [],
  },
  {
    id: "e8",
    subject: "Thank you for quick replacement",
    body: "Appreciate the fast replacement on my cracked TV-Model 4 screen. The new unit works perfectly—great service!",
    sentiment: "positive",
    customerName: "Rasmus Mortensen",
    productModel: "TV-Model 4",
    priority: "low",
    answered: true,
    history: ["Thanked for quick replacement", "Acknowledged resolution"],
    nextActions: [],
  },
  {
    id: "e9",
    subject: "Remote drains batteries fast",
    body: "The remote for TV-Model 1 goes through batteries in a week. Is this a known issue or should I request a replacement?",
    sentiment: "negative",
    customerName: "Louise Pedersen",
    productModel: "TV-Model 1",
    priority: "high",
    history: ["Remote drains batteries weekly", "Asked about replacement eligibility"],
    nextActions: ["Check serial/batch", "Offer replacement if faulty"],
  },
  {
    id: "e10",
    subject: "Corporate order questions",
    body: "We plan to outfit a small office with six TV-Model 2 units for digital signage. Can you confirm if the screens can be locked to a single input?",
    sentiment: "neutral",
    customerName: "Thomas Olesen",
    productModel: "TV-Model 2",
    priority: "medium",
    answered: true,
    history: ["Corporate signage inquiry", "Confirmed input lock options"],
    nextActions: [],
  },
  {
    id: "e11",
    subject: "Eco mode toggles off",
    body: "On TV-Model 3 the eco mode keeps disabling itself after a reboot. I'd prefer to keep it on to save power. Any ideas?",
    sentiment: "neutral",
    customerName: "Line Thomsen",
    productModel: "TV-Model 3",
    priority: "low",
    history: ["Eco mode toggles off after reboot", "Asked for persistent setting fix"],
    nextActions: ["Share persistent eco setting steps"],
  },
  {
    id: "e12",
    subject: "HDR looks washed out",
    body: "Movies on TV-Model 4 look washed out when HDR is enabled. I'm not sure if I'm missing a setting—please advise.",
    sentiment: "negative",
    customerName: "Emil Soerensen",
    productModel: "TV-Model 4",
    priority: "medium",
    history: ["HDR looks washed out", "Asked for calibration guidance"],
    nextActions: ["Send HDR preset", "Offer troubleshooting follow-up"],
  },
  {
    id: "e13",
    subject: "Praise for accessibility features",
    body: "Wanted to highlight how well the screen reader works on TV-Model 1 for my mother. Thank you for making it intuitive.",
    sentiment: "positive",
    customerName: "Malthe Iversen",
    productModel: "TV-Model 1",
    priority: "low",
    history: ["Praised accessibility features", "Acknowledged feedback"],
    nextActions: [],
  },
  {
    id: "e14",
    subject: "Warranty transfer",
    body: "I purchased TV-Model 2 second-hand. Can I transfer the remaining warranty to my name and how do I register it?",
    sentiment: "neutral",
    customerName: "Henrik Knudsen",
    productModel: "TV-Model 2",
    priority: "medium",
    history: ["Asked about second-hand warranty transfer", "Needs registration steps"],
    nextActions: ["Share transfer process", "Request proof of purchase"],
  },
  {
    id: "e15",
    subject: "App store missing key apps",
    body: "The app store on TV-Model 3 doesn't have HBO Max in Denmark. Is there a timeline for adding it?",
    sentiment: "negative",
    customerName: "Ida Berg",
    productModel: "TV-Model 3",
    priority: "medium",
    history: ["Missing HBO Max in app store", "Asked for availability timeline"],
    nextActions: ["Check app rollout status", "Provide ETA or workaround"],
  },
  {
    id: "e16",
    subject: "Positive unboxing experience",
    body: "Just unpacked TV-Model 4 and the guided setup was smooth. Thanks for the clear steps and cable labels.",
    sentiment: "positive",
    customerName: "Clara Villadsen",
    productModel: "TV-Model 4",
    priority: "low",
    history: ["Positive unboxing feedback", "Appreciated smooth setup"],
    nextActions: [],
  },
  {
    id: "e17",
    subject: "Intermittent Wi-Fi disconnects",
    body: "TV-Model 1 drops Wi-Fi every evening around the same time. Router is fine with other devices. Any troubleshooting tips?",
    sentiment: "negative",
    customerName: "Mette Friis",
    productModel: "TV-Model 1",
    priority: "high",
    history: ["Nightly Wi-Fi drops on TV-Model 1", "Other devices unaffected"],
    nextActions: ["Send Wi-Fi stability checklist", "Request router details"],
  },
  {
    id: "e18",
    subject: "Thanks for the tutorial",
    body: "The email tutorial you sent for TV-Model 2 picture calibration was super helpful. Colors look great now!",
    sentiment: "positive",
    customerName: "Pernille Vestergaard",
    productModel: "TV-Model 2",
    priority: "low",
    answered: true,
    history: ["Thanks for calibration tutorial", "Issue resolved"],
    nextActions: [],
  },
  {
    id: "e19",
    subject: "Bluetooth headphone pairing",
    body: "I'm trying to pair Bose headphones with TV-Model 3 but the TV doesn't detect them. Is there a list of supported devices?",
    sentiment: "neutral",
    customerName: "Gustav Kjeldsen",
    productModel: "TV-Model 3",
    priority: "medium",
    history: ["Bluetooth headphones not detected", "Asked for supported devices list"],
    nextActions: ["Share pairing steps", "Provide compatible devices guidance"],
  },
  {
    id: "e20",
    subject: "Screen flicker on startup",
    body: "TV-Model 4 flickers for the first 30 seconds whenever we turn it on. Happens on every boot. Can this be fixed with firmware?",
    sentiment: "negative",
    customerName: "Mille Bro",
    productModel: "TV-Model 4",
    priority: "high",
    history: ["Startup flicker for 30 seconds", "Asked if firmware fix exists"],
    nextActions: ["Check firmware version", "Share fix or escalation path"],
  },
  {
    id: "e21",
    subject: "Using TV-Model 1 as PC monitor",
    body: "Does TV-Model 1 support 1440p at 120Hz over HDMI 2.1 for PC gaming? I'm considering using it as a monitor.",
    sentiment: "neutral",
    customerName: "Viktor Bjerre",
    productModel: "TV-Model 1",
    priority: "medium",
    history: ["Asked about 1440p 120Hz over HDMI 2.1", "Considering TV as PC monitor"],
    nextActions: ["Confirm spec support", "Share setup steps if supported"],
  },
  {
    id: "e22",
    subject: "Gift purchase guidance",
    body: "Buying TV-Model 2 for my parents. Do you recommend the voice remote add-on for elderly users or is the standard remote easy enough?",
    sentiment: "positive",
    customerName: "Alberte Moller",
    productModel: "TV-Model 2",
    priority: "low",
    history: ["Gift purchase guidance for parents", "Asked about voice remote add-on"],
    nextActions: ["Recommend remote option", "Share easy-start tips"],
  },
  {
    id: "e23",
    subject: "Screen has yellow tint",
    body: "There is a persistent yellow tint on TV-Model 3 even after calibration. Is this a panel defect or a setting issue?",
    sentiment: "negative",
    customerName: "Trine Kristoffersen",
    productModel: "TV-Model 3",
    priority: "high",
    history: ["Persistent yellow tint after calibration", "Concerned about panel defect"],
    nextActions: ["Request photos/settings", "Provide correction steps"],
  },
  {
    id: "e24",
    subject: "Remote pairing steps",
    body: "I can't get the remote for TV-Model 4 to pair after replacing the batteries. Could you share the exact pairing steps?",
    sentiment: "neutral",
    customerName: "Stine Fabricius",
    productModel: "TV-Model 4",
    priority: "medium",
    answered: true,
    history: ["Remote won't pair after battery swap", "Shared pairing steps"],
    nextActions: [],
  },
  {
    id: "e25",
    subject: "Great sports picture",
    body: "TV-Model 1 handles football matches without motion blur. Really impressed—any recommended settings for Champions League nights?",
    sentiment: "positive",
    customerName: "Tobias Winther",
    productModel: "TV-Model 1",
    priority: "low",
    history: ["Praised sports picture", "Asked for Champions League settings"],
    nextActions: ["Share sports preset tips"],
  },
  {
    id: "e26",
    subject: "Delayed delivery update",
    body: "My order for TV-Model 2 was supposed to arrive last Friday but the tracking hasn't moved. Can you check the shipment status?",
    sentiment: "negative",
    customerName: "Naja Hougaard",
    productModel: "TV-Model 2",
    priority: "high",
    history: ["Delivery delay beyond promised date", "Requested shipment status update"],
    nextActions: ["Check carrier status", "Send ETA and compensation options"],
  },
];

export const customerEmails: CustomerEmail[] = emailSeeds.map((email) => ({
  ...email,
  history:
    email.history ??
    [
      `Email received: ${email.subject}`,
      `Priority: ${email.priority} • Sentiment: ${email.sentiment}`,
    ],
  nextActions:
    email.nextActions ??
    (email.answered ? [] : ["Draft reply for customer", "Confirm resolution details"]),
}));
