import { CustomerEmail } from "./types";

export const customerEmails: CustomerEmail[] = [
  {
    id: "e1",
    subject: "Ambient mode options on TV-Model 1",
    body: "Hi team, I love the panel but can't find how to enable the ambient gallery mode that was shown in the demo. Can you point me to the right menu on TV-Model 1?",
    sentiment: "positive",
    customerName: "Olivia Grant",
    productModel: "TV-Model 1",
    priority: "medium",
    answered: true,
  },
  {
    id: "e2",
    subject: "Dead pixels out of the box",
    body: "My brand new TV-Model 2 has two dead pixels in the upper right corner. I unboxed it yesterday and would like to know if this is covered under warranty or if I should return it.",
    sentiment: "negative",
    customerName: "Marcus Lee",
    productModel: "TV-Model 2",
    priority: "high",
  },
  {
    id: "e3",
    subject: "Subtitles keep disappearing",
    body: "While streaming, the subtitles on TV-Model 3 randomly disappear every few minutes. Is there a firmware update that fixes this?",
    sentiment: "neutral",
    customerName: "Priya Nair",
    productModel: "TV-Model 3",
    priority: "medium",
  },
  {
    id: "e4",
    subject: "Wall mount screws missing",
    body: "The wall mount kit for my TV-Model 4 didn't include the shorter screws mentioned in the manual. Can you send replacements or tell me which size to buy?",
    sentiment: "negative",
    customerName: "Ethan Riley",
    productModel: "TV-Model 4",
    priority: "medium",
  },
  {
    id: "e5",
    subject: "Impressed with gaming mode",
    body: "Just wanted to say the low latency gaming mode on TV-Model 1 is fantastic. Do you recommend any other settings for PS5 gameplay?",
    sentiment: "positive",
    customerName: "Sofia Nguyen",
    productModel: "TV-Model 1",
    priority: "low",
  },
  {
    id: "e6",
    subject: "Audio delay with soundbar",
    body: "I'm getting a noticeable audio delay when using my soundbar over HDMI ARC with TV-Model 2. Is there a lip sync adjustment I should try?",
    sentiment: "neutral",
    customerName: "Daniel Ortiz",
    productModel: "TV-Model 2",
    priority: "high",
  },
  {
    id: "e7",
    subject: "Picture too dim in daylight",
    body: "TV-Model 3 looks great at night but is very dim in our bright living room. Are there brightness presets for daytime use?",
    sentiment: "negative",
    customerName: "Laura Bennett",
    productModel: "TV-Model 3",
    priority: "medium",
    answered: true,
  },
  {
    id: "e8",
    subject: "Thank you for quick replacement",
    body: "Appreciate the fast replacement on my cracked TV-Model 4 screen. The new unit works perfectly—great service!",
    sentiment: "positive",
    customerName: "Noah Phillips",
    productModel: "TV-Model 4",
    priority: "low",
    answered: true,
  },
  {
    id: "e9",
    subject: "Remote drains batteries fast",
    body: "The remote for TV-Model 1 goes through batteries in a week. Is this a known issue or should I request a replacement?",
    sentiment: "negative",
    customerName: "Grace Turner",
    productModel: "TV-Model 1",
    priority: "high",
  },
  {
    id: "e10",
    subject: "Corporate order questions",
    body: "We plan to outfit a small office with six TV-Model 2 units for digital signage. Can you confirm if the screens can be locked to a single input?",
    sentiment: "neutral",
    customerName: "Anthony Delgado",
    productModel: "TV-Model 2",
    priority: "medium",
    answered: true,
  },
  {
    id: "e11",
    subject: "Eco mode toggles off",
    body: "On TV-Model 3 the eco mode keeps disabling itself after a reboot. I'd prefer to keep it on to save power. Any ideas?",
    sentiment: "neutral",
    customerName: "Lena Schmidt",
    productModel: "TV-Model 3",
    priority: "low",
  },
  {
    id: "e12",
    subject: "HDR looks washed out",
    body: "Movies on TV-Model 4 look washed out when HDR is enabled. I'm not sure if I'm missing a setting—please advise.",
    sentiment: "negative",
    customerName: "Jamal Roberts",
    productModel: "TV-Model 4",
    priority: "medium",
  },
  {
    id: "e13",
    subject: "Praise for accessibility features",
    body: "Wanted to highlight how well the screen reader works on TV-Model 1 for my mother. Thank you for making it intuitive.",
    sentiment: "positive",
    customerName: "Heather Collins",
    productModel: "TV-Model 1",
    priority: "low",
  },
  {
    id: "e14",
    subject: "Warranty transfer",
    body: "I purchased TV-Model 2 second-hand. Can I transfer the remaining warranty to my name and how do I register it?",
    sentiment: "neutral",
    customerName: "Samuel Brooks",
    productModel: "TV-Model 2",
    priority: "medium",
  },
  {
    id: "e15",
    subject: "App store missing key apps",
    body: "The app store on TV-Model 3 doesn't have HBO Max in Denmark. Is there a timeline for adding it?",
    sentiment: "negative",
    customerName: "Nora Eriksen",
    productModel: "TV-Model 3",
    priority: "medium",
  },
  {
    id: "e16",
    subject: "Positive unboxing experience",
    body: "Just unpacked TV-Model 4 and the guided setup was smooth. Thanks for the clear steps and cable labels.",
    sentiment: "positive",
    customerName: "Carlos Silva",
    productModel: "TV-Model 4",
    priority: "low",
  },
  {
    id: "e17",
    subject: "Intermittent Wi-Fi disconnects",
    body: "TV-Model 1 drops Wi-Fi every evening around the same time. Router is fine with other devices. Any troubleshooting tips?",
    sentiment: "negative",
    customerName: "Julia Petterson",
    productModel: "TV-Model 1",
    priority: "high",
  },
  {
    id: "e18",
    subject: "Thanks for the tutorial",
    body: "The email tutorial you sent for TV-Model 2 picture calibration was super helpful. Colors look great now!",
    sentiment: "positive",
    customerName: "Renee Walsh",
    productModel: "TV-Model 2",
    priority: "low",
    answered: true,
  },
  {
    id: "e19",
    subject: "Bluetooth headphone pairing",
    body: "I'm trying to pair Bose headphones with TV-Model 3 but the TV doesn't detect them. Is there a list of supported devices?",
    sentiment: "neutral",
    customerName: "Tommy Alvarez",
    productModel: "TV-Model 3",
    priority: "medium",
  },
  {
    id: "e20",
    subject: "Screen flicker on startup",
    body: "TV-Model 4 flickers for the first 30 seconds whenever we turn it on. Happens on every boot. Can this be fixed with firmware?",
    sentiment: "negative",
    customerName: "Bethany Cruz",
    productModel: "TV-Model 4",
    priority: "high",
  },
  {
    id: "e21",
    subject: "Using TV-Model 1 as PC monitor",
    body: "Does TV-Model 1 support 1440p at 120Hz over HDMI 2.1 for PC gaming? I'm considering using it as a monitor.",
    sentiment: "neutral",
    customerName: "Kevin Walsh",
    productModel: "TV-Model 1",
    priority: "medium",
  },
  {
    id: "e22",
    subject: "Gift purchase guidance",
    body: "Buying TV-Model 2 for my parents. Do you recommend the voice remote add-on for elderly users or is the standard remote easy enough?",
    sentiment: "positive",
    customerName: "Diana Novak",
    productModel: "TV-Model 2",
    priority: "low",
  },
  {
    id: "e23",
    subject: "Screen has yellow tint",
    body: "There is a persistent yellow tint on TV-Model 3 even after calibration. Is this a panel defect or a setting issue?",
    sentiment: "negative",
    customerName: "Adrian Fox",
    productModel: "TV-Model 3",
    priority: "high",
  },
  {
    id: "e24",
    subject: "Remote pairing steps",
    body: "I can't get the remote for TV-Model 4 to pair after replacing the batteries. Could you share the exact pairing steps?",
    sentiment: "neutral",
    customerName: "Marie Dupont",
    productModel: "TV-Model 4",
    priority: "medium",
    answered: true,
  },
  {
    id: "e25",
    subject: "Great sports picture",
    body: "TV-Model 1 handles football matches without motion blur. Really impressed—any recommended settings for Champions League nights?",
    sentiment: "positive",
    customerName: "Jonas Mikkelsen",
    productModel: "TV-Model 1",
    priority: "low",
  },
  {
    id: "e26",
    subject: "Delayed delivery update",
    body: "My order for TV-Model 2 was supposed to arrive last Friday but the tracking hasn't moved. Can you check the shipment status?",
    sentiment: "negative",
    customerName: "Patricia Cole",
    productModel: "TV-Model 2",
    priority: "high",
  },
  {
    id: "e27",
    subject: "Energy consumption details",
    body: "Before installing TV-Model 3 in our vacation home, could you share typical kWh usage per month when used 3 hours daily?",
    sentiment: "neutral",
    customerName: "Stefan Müller",
    productModel: "TV-Model 3",
    priority: "low",
  },
  {
    id: "e28",
    subject: "Thank you for accessibility support",
    body: "Appreciate how responsive the customer support was in explaining closed captions on TV-Model 4. It made my dad's day.",
    sentiment: "positive",
    customerName: "Isabella Rossi",
    productModel: "TV-Model 4",
    priority: "low",
    answered: true,
  },
  {
    id: "e29",
    subject: "Stuck pixels after two months",
    body: "TV-Model 1 developed stuck pixels near the center. It's past the return window—can this be repaired under warranty?",
    sentiment: "negative",
    customerName: "Mateo Ruiz",
    productModel: "TV-Model 1",
    priority: "high",
  },
  {
    id: "e30",
    subject: "Streaming quality drops",
    body: "On TV-Model 2, Netflix quality keeps downgrading even though our connection is stable. Do I need to adjust any bandwidth settings?",
    sentiment: "negative",
    customerName: "Sinead O'Connor",
    productModel: "TV-Model 2",
    priority: "medium",
  },
  {
    id: "e31",
    subject: "Corporate accessibility request",
    body: "We're considering TV-Model 3 displays for an office. Do they support live captions for HDMI inputs for town halls?",
    sentiment: "neutral",
    customerName: "George Patel",
    productModel: "TV-Model 3",
    priority: "medium",
  },
  {
    id: "e32",
    subject: "Good value for rental unit",
    body: "Installed TV-Model 4 in our rental apartment and tenants love the interface. Any tips to lock down settings between guests?",
    sentiment: "positive",
    customerName: "Anna Kowalski",
    productModel: "TV-Model 4",
    priority: "medium",
  },
  {
    id: "e33",
    subject: "Random reboots overnight",
    body: "TV-Model 1 reboots itself at 3 AM which wakes the room with the start-up chime. How do I disable scheduled updates?",
    sentiment: "negative",
    customerName: "Felix Wagner",
    productModel: "TV-Model 1",
    priority: "medium",
    answered: true,
  },
  {
    id: "e34",
    subject: "Picture presets for cinema",
    body: "Can you share recommended picture presets on TV-Model 2 for a dark home theater? I'm chasing accurate color for films.",
    sentiment: "positive",
    customerName: "Elena Papadopoulos",
    productModel: "TV-Model 2",
    priority: "low",
  },
  {
    id: "e35",
    subject: "Vertical banding issue",
    body: "TV-Model 3 shows faint vertical bands on gray backgrounds. It's subtle but noticeable during sports. Is this typical?",
    sentiment: "negative",
    customerName: "Oskar Lind",
    productModel: "TV-Model 3",
    priority: "medium",
  },
  {
    id: "e36",
    subject: "CEC turning on console",
    body: "Whenever I power on TV-Model 4 it also starts my PS5 even if I don't want to game. How can I disable CEC?",
    sentiment: "neutral",
    customerName: "Riley Carter",
    productModel: "TV-Model 4",
    priority: "low",
  },
  {
    id: "e37",
    subject: "Brightness spikes after update",
    body: "After the latest firmware, TV-Model 1 sometimes jumps to maximum brightness mid-show. This is uncomfortable—can I roll back?",
    sentiment: "negative",
    customerName: "Camille Laurent",
    productModel: "TV-Model 1",
    priority: "high",
  },
  {
    id: "e38",
    subject: "Quick thanks for concierge support",
    body: "Your team guided me through calibrating TV-Model 2 over chat in under 10 minutes. Stellar experience!",
    sentiment: "positive",
    customerName: "Mikkel Sørensen",
    productModel: "TV-Model 2",
    priority: "low",
    answered: true,
  },
  {
    id: "e39",
    subject: "Low audio over optical",
    body: "Using optical out on TV-Model 3 to a receiver results in very low volume even at max. Any setting to boost the signal?",
    sentiment: "negative",
    customerName: "Harper Diaz",
    productModel: "TV-Model 3",
    priority: "medium",
  },
  {
    id: "e40",
    subject: "Wall mount height guidance",
    body: "Just installed TV-Model 4 in our studio. Any guidelines on eye-level height and tilt for optimal viewing distance of 3 meters?",
    sentiment: "neutral",
    customerName: "Victor Hansen",
    productModel: "TV-Model 4",
    priority: "low",
  },
];
