import { Review } from "./types";

export const reviews: Review[] = [
  {
    id: "1",
    text: "Absolutely love this TV! The picture quality is stunning, colors are vibrant, and the sound is crystal clear. Best purchase I've made this year. Highly recommend!",
    rating: 5,
    sentiment: "positive",
    customerName: "Camilla Frederiksen",
    productModel: "TV-Model 1",
  },
  {
    id: "2",
    text: "Terrible experience. The TV arrived with a cracked screen and customer service was unhelpful. Had to return it immediately. Very disappointed.",
    rating: 1,
    sentiment: "negative",
    customerName: "Rasmus Kaer",
    productModel: "TV-Model 2",
  },
  {
    id: "3",
    text: "Decent TV for the price. Picture quality is okay, but the smart features are a bit slow. It does the job but nothing special.",
    rating: 3,
    sentiment: "neutral",
    customerName: "Malene Borch",
    productModel: "TV-Model 3",
  },
  {
    id: "4",
    text: "The remote control stopped working after just 2 weeks. The TV itself is fine, but this is frustrating. Should I have to buy a new remote so soon?",
    rating: 2,
    sentiment: "negative",
    customerName: "Jonas Riis",
    productModel: "TV-Model 4",
  },
  {
    id: "5",
    text: "Amazing value for money! The 4K resolution is incredible, and the built-in apps work flawlessly. Setup was super easy. Couldn't be happier!",
    rating: 5,
    sentiment: "positive",
    customerName: "Pernille Lind",
    productModel: "TV-Model 1",
  },
  {
    id: "6",
    text: "The TV has good picture quality, but the viewing angles are poor. If you're not sitting directly in front, the colors look washed out. Not ideal for a living room.",
    rating: 3,
    sentiment: "neutral",
    customerName: "Anders Krog",
    productModel: "TV-Model 2",
  },
  {
    id: "7",
    text: "Worst TV I've ever owned. Constant software crashes, apps freeze regularly, and the Wi-Fi connection drops constantly. Save your money and buy something else.",
    rating: 1,
    sentiment: "negative",
    customerName: "Mette Holmgaard",
    productModel: "TV-Model 3",
  },
  {
    id: "8",
    text: "Perfect for gaming! Low input lag and smooth motion handling. The HDR looks fantastic. My friends are all jealous of this setup.",
    rating: 5,
    sentiment: "positive",
    customerName: "Soren Hald",
    productModel: "TV-Model 4",
  },
  {
    id: "9",
    text: "The sound quality is really poor. Had to buy a soundbar immediately. For the price, I expected better built-in speakers. Picture is good though.",
    rating: 3,
    sentiment: "neutral",
    customerName: "Stine Vestergaard",
    productModel: "TV-Model 1",
  },
  {
    id: "10",
    text: "Excellent customer service when I had a question about setup. The TV itself is great - bright, clear, and the smart interface is intuitive. Very satisfied!",
    rating: 5,
    sentiment: "positive",
    customerName: "Jacob Moller",
    productModel: "TV-Model 2",
  },
  {
    id: "11",
    text: "Dead pixels appeared after 3 months. Contacted support but they said it's not covered under warranty. Very disappointed with both the product and service.",
    rating: 2,
    sentiment: "negative",
    customerName: "Ida Kragh",
    productModel: "TV-Model 3",
  },
  {
    id: "12",
    text: "Good TV overall. The picture is nice and the price was reasonable. Some of the smart features could be faster, but it's acceptable for daily use.",
    rating: 4,
    sentiment: "positive",
    customerName: "Frederik Dam",
    productModel: "TV-Model 4",
  },
  {
    id: "13",
    text: "The TV overheats after being on for a few hours. I'm worried about safety. This shouldn't happen with a brand new television. Very concerning.",
    rating: 2,
    sentiment: "negative",
    customerName: "Louise Bak",
    productModel: "TV-Model 1",
  },
  {
    id: "14",
    text: "Love the design - it's sleek and modern. The picture quality is excellent, especially for movies. The only downside is the limited app selection compared to competitors.",
    rating: 4,
    sentiment: "positive",
    customerName: "Tobias Birk",
    productModel: "TV-Model 2",
  },
  {
    id: "15",
    text: "Average TV. Does what it's supposed to do but nothing stands out. The remote feels cheap and the menu system is confusing. It works, but I expected more.",
    rating: 3,
    sentiment: "neutral",
    customerName: "Silke Falk",
    productModel: "TV-Model 3",
  },
  {
    id: "16",
    text: "Outstanding picture quality! The colors are so vivid and realistic. Watching nature documentaries on this TV is like looking through a window. Absolutely worth every penny!",
    rating: 5,
    sentiment: "positive",
    customerName: "Kasper Seidel",
    productModel: "TV-Model 1",
  },
  {
    id: "17",
    text: "The backlight bleeding is terrible. Dark scenes look awful with bright spots around the edges. For a TV at this price point, this is unacceptable quality control.",
    rating: 1,
    sentiment: "negative",
    customerName: "Julie Aagaard",
    productModel: "TV-Model 4",
  },
  {
    id: "18",
    text: "It's an okay TV. The interface is user-friendly and setup was straightforward. Picture quality is decent but not amazing. Gets the job done for everyday watching.",
    rating: 3,
    sentiment: "neutral",
    customerName: "Mikkel Bo",
    productModel: "TV-Model 2",
  },
  {
    id: "19",
    text: "Brilliant TV for sports! The motion handling is superb - no blur during fast action. The screen is bright enough even in a sunny room. Very impressed!",
    rating: 5,
    sentiment: "positive",
    customerName: "Sofie Laursen",
    productModel: "TV-Model 3",
  },
  {
    id: "20",
    text: "HDMI ports stopped working after 6 months. Now I can't connect my gaming console. Support said it would cost almost as much as a new TV to repair. Total waste of money.",
    rating: 1,
    sentiment: "negative",
    customerName: "Christian Bay",
    productModel: "TV-Model 1",
  },
  {
    id: "21",
    text: "The TV is fine for basic use. Netflix and YouTube work well. The picture isn't the sharpest I've seen, but it's acceptable. Nothing to complain about, nothing to rave about either.",
    rating: 3,
    sentiment: "neutral",
    customerName: "Nanna Krogh",
    productModel: "TV-Model 4",
  },
  {
    id: "22",
    text: "Fantastic smart features! Voice control works perfectly, and the app selection is comprehensive. The picture quality exceeds my expectations. Highly recommend for tech enthusiasts!",
    rating: 5,
    sentiment: "positive",
    customerName: "Mads Dalgaard",
    productModel: "TV-Model 2",
  },
  {
    id: "23",
    text: "The screen has a weird yellowish tint that I can't adjust away. Colors don't look natural at all. Very disappointed with the color accuracy. Should have bought a different brand.",
    rating: 2,
    sentiment: "negative",
    customerName: "Helene Brask",
    productModel: "TV-Model 3",
  },
  {
    id: "24",
    text: "Solid mid-range TV. The bezels are thin which looks modern. Sound is mediocre but acceptable. For the price, it's a reasonable purchase but don't expect premium features.",
    rating: 3,
    sentiment: "neutral",
    customerName: "Nikolaj Ibsen",
    productModel: "TV-Model 1",
  },
  {
    id: "25",
    text: "Best TV I've ever owned! The HDR performance is incredible - bright highlights and deep blacks. Streaming is seamless and the interface is lightning fast. 10/10 would buy again!",
    rating: 5,
    sentiment: "positive",
    customerName: "Anne Katrine Olesen",
    productModel: "TV-Model 4",
  },
  {
    id: "26",
    text: "Audio and video are constantly out of sync. Tried every setting and nothing fixes it. Makes watching anything unbearable. Returning this as soon as possible.",
    rating: 1,
    sentiment: "negative",
    customerName: "Emil Vang",
    productModel: "TV-Model 2",
  },
  {
    id: "27",
    text: "It does what it needs to do. The smart features are a bit limited compared to other brands. Picture is clear enough for news and sitcoms. Not bad, not great.",
    rating: 3,
    sentiment: "neutral",
    customerName: "Karoline Brandt",
    productModel: "TV-Model 3",
  },
  {
    id: "28",
    text: "Absolutely stunning design! Ultra-thin profile looks amazing on the wall. The picture quality matches the aesthetics - crisp, bright, and beautiful. Guests always compliment it!",
    rating: 5,
    sentiment: "positive",
    customerName: "Simon Markvad",
    productModel: "TV-Model 1",
  },
  {
    id: "29",
    text: "The TV randomly turns off by itself. Happens multiple times a day. Customer service was no help - just told me to reset it, which doesn't work. Very frustrating experience.",
    rating: 2,
    sentiment: "negative",
    customerName: "Ditte Hjorth",
    productModel: "TV-Model 4",
  },
  {
    id: "30",
    text: "Decent value for money. The picture is clear and colors are fairly accurate. The remote could be better designed. Overall, it's a competent TV without any standout features.",
    rating: 3,
    sentiment: "neutral",
    customerName: "Philip Kroer",
    productModel: "TV-Model 2",
  },
  {
    id: "31",
    text: "Phenomenal for movie nights! The contrast ratio is excellent and the upscaling of older content is impressive. The built-in speakers are surprisingly good too. Love it!",
    rating: 5,
    sentiment: "positive",
    customerName: "Alma Rosendahl",
    productModel: "TV-Model 3",
  },
  {
    id: "32",
    text: "Screen cracked during normal use - we didn't drop it or hit it. The manufacturer refused warranty coverage claiming physical damage. Terrible product quality and worse customer support.",
    rating: 1,
    sentiment: "negative",
    customerName: "Victor Lemming",
    productModel: "TV-Model 1",
  },
  {
    id: "33",
    text: "The TV is okay. Setup was easy and the menus are straightforward. Picture quality is average - good enough for casual viewing. Nothing special but it works fine.",
    rating: 3,
    sentiment: "neutral",
    customerName: "Trine Bang",
    productModel: "TV-Model 4",
  },
  {
    id: "34",
    text: "Incredible gaming experience! The 120Hz refresh rate makes everything buttery smooth. Low latency and great color accuracy. Every gamer should consider this TV!",
    rating: 5,
    sentiment: "positive",
    customerName: "Magnus Seier",
    productModel: "TV-Model 2",
  },
  {
    id: "35",
    text: "The brightness is way too low even at maximum settings. Can barely see anything during daytime. The contrast is poor too. Not suitable for bright rooms at all.",
    rating: 2,
    sentiment: "negative",
    customerName: "Cecilie Norup",
    productModel: "TV-Model 3",
  },
];

