import { Review } from "./types";

export const reviews: Review[] = [
  {
    id: "1",
    text: "Absolutely love this TV! The picture quality is stunning, colors are vibrant, and the sound is crystal clear. Best purchase I've made this year. Highly recommend!",
    rating: 5,
    sentiment: "positive",
    customerName: "Sarah Jenkins",
    productModel: "TV-Model 1",
  },
  {
    id: "2",
    text: "Terrible experience. The TV arrived with a cracked screen and customer service was unhelpful. Had to return it immediately. Very disappointed.",
    rating: 1,
    sentiment: "negative",
    customerName: "Mike Thompson",
    productModel: "TV-Model 2",
  },
  {
    id: "3",
    text: "Decent TV for the price. Picture quality is okay, but the smart features are a bit slow. It does the job but nothing special.",
    rating: 3,
    sentiment: "neutral",
    customerName: "Emily Chen",
    productModel: "TV-Model 3",
  },
  {
    id: "4",
    text: "The remote control stopped working after just 2 weeks. The TV itself is fine, but this is frustrating. Should I have to buy a new remote so soon?",
    rating: 2,
    sentiment: "negative",
    customerName: "David Wilson",
    productModel: "TV-Model 4",
  },
  {
    id: "5",
    text: "Amazing value for money! The 4K resolution is incredible, and the built-in apps work flawlessly. Setup was super easy. Couldn't be happier!",
    rating: 5,
    sentiment: "positive",
    customerName: "Jessica Martinez",
    productModel: "TV-Model 1",
  },
  {
    id: "6",
    text: "The TV has good picture quality, but the viewing angles are poor. If you're not sitting directly in front, the colors look washed out. Not ideal for a living room.",
    rating: 3,
    sentiment: "neutral",
    customerName: "Robert Taylor",
    productModel: "TV-Model 2",
  },
  {
    id: "7",
    text: "Worst TV I've ever owned. Constant software crashes, apps freeze regularly, and the Wi-Fi connection drops constantly. Save your money and buy something else.",
    rating: 1,
    sentiment: "negative",
    customerName: "Lisa Anderson",
    productModel: "TV-Model 3",
  },
  {
    id: "8",
    text: "Perfect for gaming! Low input lag and smooth motion handling. The HDR looks fantastic. My friends are all jealous of this setup.",
    rating: 5,
    sentiment: "positive",
    customerName: "Kevin White",
    productModel: "TV-Model 4",
  },
  {
    id: "9",
    text: "The sound quality is really poor. Had to buy a soundbar immediately. For the price, I expected better built-in speakers. Picture is good though.",
    rating: 3,
    sentiment: "neutral",
    customerName: "Amanda Thomas",
    productModel: "TV-Model 1",
  },
  {
    id: "10",
    text: "Excellent customer service when I had a question about setup. The TV itself is great - bright, clear, and the smart interface is intuitive. Very satisfied!",
    rating: 5,
    sentiment: "positive",
    customerName: "Chris Garcia",
    productModel: "TV-Model 2",
  },
  {
    id: "11",
    text: "Dead pixels appeared after 3 months. Contacted support but they said it's not covered under warranty. Very disappointed with both the product and service.",
    rating: 2,
    sentiment: "negative",
    customerName: "Patricia Robinson",
    productModel: "TV-Model 3",
  },
  {
    id: "12",
    text: "Good TV overall. The picture is nice and the price was reasonable. Some of the smart features could be faster, but it's acceptable for daily use.",
    rating: 4,
    sentiment: "positive",
    customerName: "Daniel Lee",
    productModel: "TV-Model 4",
  },
  {
    id: "13",
    text: "The TV overheats after being on for a few hours. I'm worried about safety. This shouldn't happen with a brand new television. Very concerning.",
    rating: 2,
    sentiment: "negative",
    customerName: "Jennifer Clark",
    productModel: "TV-Model 1",
  },
  {
    id: "14",
    text: "Love the design - it's sleek and modern. The picture quality is excellent, especially for movies. The only downside is the limited app selection compared to competitors.",
    rating: 4,
    sentiment: "positive",
    customerName: "Brian Lewis",
    productModel: "TV-Model 2",
  },
  {
    id: "15",
    text: "Average TV. Does what it's supposed to do but nothing stands out. The remote feels cheap and the menu system is confusing. It works, but I expected more.",
    rating: 3,
    sentiment: "neutral",
    customerName: "Megan Walker",
    productModel: "TV-Model 3",
  },
];

